
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry Pantalla;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button bvaciar;

	private global::Gtk.Button bc;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button bsiete;

	private global::Gtk.Button bocho;

	private global::Gtk.Button bnueve;

	private global::Gtk.Button bdividir;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button bcuatro;

	private global::Gtk.Button bcinco;

	private global::Gtk.Button bseis;

	private global::Gtk.Button bmulti;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button buno;

	private global::Gtk.Button bdos;

	private global::Gtk.Button btres;

	private global::Gtk.Button bresta;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button bpunto;

	private global::Gtk.Button bcero;

	private global::Gtk.Button bigual;

	private global::Gtk.Button bsuma;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 0;
		this.HeightRequest = 0;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.HeightRequest = 50;
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora 2 .0");
		this.vbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Pantalla = new global::Gtk.Entry();
		this.Pantalla.CanFocus = true;
		this.Pantalla.Name = "Pantalla";
		this.Pantalla.IsEditable = false;
		this.Pantalla.InvisibleChar = '•';
		this.vbox1.Add(this.Pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Pantalla]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.bvaciar = new global::Gtk.Button();
		this.bvaciar.WidthRequest = 213;
		this.bvaciar.CanFocus = true;
		this.bvaciar.Name = "bvaciar";
		this.bvaciar.UseUnderline = true;
		this.bvaciar.Label = global::Mono.Unix.Catalog.GetString("Vaciar");
		this.hbox1.Add(this.bvaciar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.bvaciar]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.bc = new global::Gtk.Button();
		this.bc.WidthRequest = 70;
		this.bc.CanFocus = true;
		this.bc.Name = "bc";
		this.bc.UseUnderline = true;
		this.bc.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox1.Add(this.bc);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.bc]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.bsiete = new global::Gtk.Button();
		this.bsiete.WidthRequest = 66;
		this.bsiete.HeightRequest = 0;
		this.bsiete.CanFocus = true;
		this.bsiete.Name = "bsiete";
		this.bsiete.UseUnderline = true;
		this.bsiete.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox2.Add(this.bsiete);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.bsiete]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.bocho = new global::Gtk.Button();
		this.bocho.WidthRequest = 67;
		this.bocho.HeightRequest = 0;
		this.bocho.CanFocus = true;
		this.bocho.Name = "bocho";
		this.bocho.UseUnderline = true;
		this.bocho.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox2.Add(this.bocho);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.bocho]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.bnueve = new global::Gtk.Button();
		this.bnueve.WidthRequest = 67;
		this.bnueve.CanFocus = true;
		this.bnueve.Name = "bnueve";
		this.bnueve.UseUnderline = true;
		this.bnueve.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox2.Add(this.bnueve);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.bnueve]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.bdividir = new global::Gtk.Button();
		this.bdividir.WidthRequest = 70;
		this.bdividir.CanFocus = true;
		this.bdividir.Name = "bdividir";
		this.bdividir.UseUnderline = true;
		this.bdividir.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox2.Add(this.bdividir);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.bdividir]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.bcuatro = new global::Gtk.Button();
		this.bcuatro.WidthRequest = 67;
		this.bcuatro.CanFocus = true;
		this.bcuatro.Name = "bcuatro";
		this.bcuatro.UseUnderline = true;
		this.bcuatro.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox3.Add(this.bcuatro);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.bcuatro]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.bcinco = new global::Gtk.Button();
		this.bcinco.WidthRequest = 67;
		this.bcinco.CanFocus = true;
		this.bcinco.Name = "bcinco";
		this.bcinco.UseUnderline = true;
		this.bcinco.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox3.Add(this.bcinco);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.bcinco]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.bseis = new global::Gtk.Button();
		this.bseis.WidthRequest = 67;
		this.bseis.CanFocus = true;
		this.bseis.Name = "bseis";
		this.bseis.UseUnderline = true;
		this.bseis.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox3.Add(this.bseis);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.bseis]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.bmulti = new global::Gtk.Button();
		this.bmulti.WidthRequest = 70;
		this.bmulti.CanFocus = true;
		this.bmulti.Name = "bmulti";
		this.bmulti.UseUnderline = true;
		this.bmulti.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox3.Add(this.bmulti);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.bmulti]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.buno = new global::Gtk.Button();
		this.buno.WidthRequest = 66;
		this.buno.CanFocus = true;
		this.buno.Name = "buno";
		this.buno.UseUnderline = true;
		this.buno.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox4.Add(this.buno);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buno]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.bdos = new global::Gtk.Button();
		this.bdos.WidthRequest = 67;
		this.bdos.CanFocus = true;
		this.bdos.Name = "bdos";
		this.bdos.UseUnderline = true;
		this.bdos.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox4.Add(this.bdos);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.bdos]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btres = new global::Gtk.Button();
		this.btres.WidthRequest = 67;
		this.btres.CanFocus = true;
		this.btres.Name = "btres";
		this.btres.UseUnderline = true;
		this.btres.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox4.Add(this.btres);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btres]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.bresta = new global::Gtk.Button();
		this.bresta.WidthRequest = 70;
		this.bresta.CanFocus = true;
		this.bresta.Name = "bresta";
		this.bresta.UseUnderline = true;
		this.bresta.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox4.Add(this.bresta);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.bresta]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w20.Position = 5;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.bpunto = new global::Gtk.Button();
		this.bpunto.WidthRequest = 66;
		this.bpunto.CanFocus = true;
		this.bpunto.Name = "bpunto";
		this.bpunto.UseUnderline = true;
		this.bpunto.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox5.Add(this.bpunto);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.bpunto]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.bcero = new global::Gtk.Button();
		this.bcero.WidthRequest = 67;
		this.bcero.CanFocus = true;
		this.bcero.Name = "bcero";
		this.bcero.UseUnderline = true;
		this.bcero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox5.Add(this.bcero);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.bcero]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.bigual = new global::Gtk.Button();
		this.bigual.WidthRequest = 67;
		this.bigual.CanFocus = true;
		this.bigual.Name = "bigual";
		this.bigual.UseUnderline = true;
		this.bigual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox5.Add(this.bigual);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.bigual]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.bsuma = new global::Gtk.Button();
		this.bsuma.WidthRequest = 70;
		this.bsuma.CanFocus = true;
		this.bsuma.Name = "bsuma";
		this.bsuma.UseUnderline = true;
		this.bsuma.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox5.Add(this.bsuma);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.bsuma]));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w25.Position = 6;
		w25.Expand = false;
		w25.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 297;
		this.DefaultHeight = 290;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.bvaciar.Clicked += new global::System.EventHandler(this.OnBvaciarClicked);
		this.bc.Clicked += new global::System.EventHandler(this.OnBcClicked);
		this.bsiete.Clicked += new global::System.EventHandler(this.OnBsieteClicked);
		this.bocho.Clicked += new global::System.EventHandler(this.OnBochoClicked);
		this.bnueve.Clicked += new global::System.EventHandler(this.OnBnueveClicked);
		this.bdividir.Clicked += new global::System.EventHandler(this.OnBdividirClicked);
		this.bcuatro.Clicked += new global::System.EventHandler(this.OnBcuatroClicked);
		this.bcinco.Clicked += new global::System.EventHandler(this.OnBcincoClicked);
		this.bseis.Clicked += new global::System.EventHandler(this.OnBseisClicked);
		this.bmulti.Clicked += new global::System.EventHandler(this.OnBmultiClicked);
		this.buno.Clicked += new global::System.EventHandler(this.OnBunoClicked);
		this.bdos.Clicked += new global::System.EventHandler(this.OnBdosClicked);
		this.btres.Clicked += new global::System.EventHandler(this.OnBtresClicked);
		this.bresta.Clicked += new global::System.EventHandler(this.OnBrestaClicked);
		this.bpunto.Clicked += new global::System.EventHandler(this.OnBpuntoClicked);
		this.bcero.Clicked += new global::System.EventHandler(this.OnBceroClicked);
		this.bigual.Clicked += new global::System.EventHandler(this.OnBigualClicked);
		this.bsuma.Clicked += new global::System.EventHandler(this.OnBsumaClicked);
	}
}
