
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry text;

	private global::Gtk.Button BSaludar;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Entry entry2;

	private global::Gtk.Button BAleatorio;

	private global::Gtk.Button BSalir;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.WidthRequest = 22;
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Mi primer programa");
		this.vbox5.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.text = new global::Gtk.Entry();
		this.text.CanFocus = true;
		this.text.Name = "text";
		this.text.IsEditable = true;
		this.text.InvisibleChar = '•';
		this.hbox1.Add(this.text);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.text]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.BSaludar = new global::Gtk.Button();
		this.BSaludar.WidthRequest = 135;
		this.BSaludar.HeightRequest = 50;
		this.BSaludar.CanFocus = true;
		this.BSaludar.Name = "BSaludar";
		this.BSaludar.UseUnderline = true;
		this.BSaludar.BorderWidth = ((uint)(3));
		this.BSaludar.Label = global::Mono.Unix.Catalog.GetString("Saludar");
		this.hbox1.Add(this.BSaludar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BSaludar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox5.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = false;
		this.entry2.InvisibleChar = '•';
		this.hbox2.Add(this.entry2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entry2]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BAleatorio = new global::Gtk.Button();
		this.BAleatorio.CanFocus = true;
		this.BAleatorio.Name = "BAleatorio";
		this.BAleatorio.UseUnderline = true;
		this.BAleatorio.Label = global::Mono.Unix.Catalog.GetString("Aleatorio");
		this.hbox2.Add(this.BAleatorio);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BAleatorio]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.BSalir = new global::Gtk.Button();
		this.BSalir.CanFocus = true;
		this.BSalir.Name = "BSalir";
		this.BSalir.UseUnderline = true;
		this.BSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.hbox2.Add(this.BSalir);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BSalir]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox5.Add(this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.Add(this.vbox5);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 426;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BSaludar.Clicked += new global::System.EventHandler(this.OnBSaludarClicked);
		this.BAleatorio.Clicked += new global::System.EventHandler(this.OnBAleatorioClicked);
		this.BSalir.Clicked += new global::System.EventHandler(this.OnBSalirClicked);
	}
}
