
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vBox;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label Text;

	private global::Gtk.Button Bjugar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vBox = new global::Gtk.VBox();
		this.vBox.Name = "vBox";
		this.vBox.Spacing = 6;
		this.vBox.BorderWidth = ((uint)(6));
		// Container child vBox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Text = new global::Gtk.Label();
		this.Text.Name = "Text";
		this.Text.LabelProp = global::Mono.Unix.Catalog.GetString("Mi primera aplicacion");
		this.hbox1.Add(this.Text);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Text]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Bjugar = new global::Gtk.Button();
		this.Bjugar.WidthRequest = 90;
		this.Bjugar.HeightRequest = 49;
		this.Bjugar.CanFocus = true;
		this.Bjugar.Name = "Bjugar";
		this.Bjugar.UseUnderline = true;
		this.Bjugar.Label = global::Mono.Unix.Catalog.GetString("Jugar");
		this.hbox1.Add(this.Bjugar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Bjugar]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vBox.Add(this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vBox[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 381;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Bjugar.Clicked += new global::System.EventHandler(this.OnBjugarClicked);
	}
}
